export const getTableColumns = (t) => [
    { key: "id", label: t("#") },
    { key: "name", label: t("Name") },
    { key: "email", label: t("Email") },
    { key: "phone", label: t("Phone"), sortable: false },
    { key: "joiningDate", label: t("Joining Date") },
    { key: "notes", label: t("Note"), sortable: false },
    { key: "social", label: t("Social"), sortable: false },
    { key: "status", label: t("Status") },
    { key: "action", label: t("Action"), sortable: false },
];

export const dealsData = [
    {
        id: 201,
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        status: "New",
        value: 50000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 102,
        name: "Garage Master Mall",
        email: "garage.master.mall@example.com",
        phone: "555-5678",
        value: 760000,
        joiningDate: "2025-09-14",
        notes: "Requested demo",
        source: "Google Campaign",
        status: "Approved",
        facebook: "asd",
        instagram: "",
        website: "asd",
        isFinished: true,
    },
    {
        id: 103,
        name: "Pizza Hut",
        email: "pizzahut@example.com",
        phone: "555-8765",
        value: 430000,
        joiningDate: "2025-09-13",
        notes: "Wants enterprise plan",
        source: "LinkedIn Outreach",
        status: "New",
        facebook: "",
        instagram: "ss",
        website: "",
        isFinished: false,
    },
    {
        id: 202,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Approved",
        value: 120000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: true,
    },
    {
        id: 205,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Approved",
        value: 165000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 106,
        name: "Starbucks",
        email: "starbucks@example.com",
        phone: "555-2468",
        joiningDate: "2025-09-10",
        notes: "Interested in trial",
        source: "Instagram Ads",
        value: 32000,
        status: "Design",
        facebook: "",
        instagram: "",
        website: "ss",
        isFinished: false,
    },
    {
        id: 107,
        name: "Subway",
        email: "subway@example.com",
        phone: "555-1357",
        joiningDate: "2025-09-09",
        value: 65000,
        notes: "Needs integration support",
        source: "YouTube Ads",
        status: "Targeting",
        facebook: "",
        instagram: "",
        website: "",
        isFinished: true,
    },
    {
        id: 212,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Copy Writing",
        value: 32000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 209,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "New",
        value: 850000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 245,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Copy Writing",
        value: 80000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: true,
    },
    {
        id: 289,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Pending",
        value: 55000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 223,
        name: "Metroshin",
        email: "metroshin@example.com",
        phone: "555-8765",
        value: 600000,
        joiningDate: "2025-09-13",
        notes: "Wants enterprise plan",
        source: "LinkedIn Outreach",
        status: "New",
        facebook: "",
        instagram: "ss",
        website: "",
        isFinished: false,
    },
];

export const expensesColumns = [
    { key: "dealId", label: "Deal", sortable: true },
    { key: "salesManager", label: "Sales Manager / PM", sortable: true },
    { key: "copyWriter", label: "Copywriter", sortable: true },
    { key: "designer", label: "Designer", sortable: true },
    { key: "targeting", label: "Targeting", sortable: true },
    { key: "shooting", label: "Shooting", sortable: true },
    { key: "other", label: "Other (Notes)", sortable: false },
    { key: "total", label: "Total", sortable: true },
    { key: "action", label: "Action", sortable: false },
];

export const rolesConfig = {
    Admin: { access: ["all"] },
    Manager: { access: ["all"] },
    SalesManager: { access: ["clients", "campaign", "deals", "packages"], restricted: ["statistics"] },
    PM: { access: ["clients", "campaign", "deals", "packages"], restricted: ["statistics"] },
    Copywriter: { access: ["Copy Writing"], restricted: ["all"] },
    Reelmaker: { access: ["Shooting"], restricted: ["all"] },
    Designer: { access: ["Design"], restricted: ["all"] },
    Targetolog: { access: ["Targeting"], restricted: ["all"] }
};