export const clientsData = [
    {
        id: 70263,
        name: "Adelaide Scott",
        email: "smith_jadyn@gmail.com",
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        status: "New",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 59991,
        name: "Minerva Atkins",
        email: "murray_kianna@gmail.com",
        phone: "481-648-1385",
        joiningDate: "2025-09-14",
        notes: "04 Jeff Estate",
        status: "New",
        facebook: "ssss",
        instagram: "asd",
        website: "sa",
    },
    {
        id: 74320,
        name: "Lottie Watts",
        email: "bashirian.laurenta@gmail.com",
        phone: "768-939-3835",
        joiningDate: "2025-09-14",
        notes: "879 Lorenzo Meadow Apt. 812",
        status: "Approved",
        facebook: "",
        instagram: "",
        website: "ssas",
    },
    {
        id: 38632,
        name: "Bernard Pratt",
        email: "arielle_schiller@imogene.net",
        phone: "199-463-4077",
        joiningDate: "2025-09-14",
        notes: "270 Suzanne Centers Apt. 440",
        status: "New",
        facebook: "sssss",
        instagram: "",
        website: "",
    },
    {
        id: 60348,
        name: "Norman Fowler",
        email: "krajcik_mavis@june.net",
        phone: "344-817-4239",
        joiningDate: "2025-09-14",
        notes: "30 Albina Drive Apt. 284",
        status: "New",
        facebook: "asa",
        instagram: "as",
        website: "",
    },
    {
        id: 70223,
        name: "Scott",
        email: "smith_jadyn@gmail.com",
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        status: "New",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 591,
        name: "Minerva XX Atkins",
        email: "murray_kianna@gmail.com",
        phone: "481-648-1385",
        joiningDate: "2025-09-14",
        notes: "04 Jeff Estate",
        status: "New",
        facebook: "ssss",
        instagram: "asd",
        website: "sa",
    },
    {
        id: 7120,
        name: "Lottie Watts",
        email: "bashirian.laurenta@gmail.com",
        phone: "768-939-3835",
        joiningDate: "2025-09-14",
        notes: "879 Lorenzo Meadow Apt. 812",
        status: "Approved",
        facebook: "",
        instagram: "",
        website: "ssas",
    },
    {
        id: 332,
        name: "Bernard Pssratt",
        email: "arielle_schiller@imogene.net",
        phone: "199-463-4077",
        joiningDate: "2025-09-14",
        notes: "270 Suzanne Centers Apt. 440",
        status: "New",
        facebook: "sssss",
        instagram: "",
        website: "",
    },
    {
        id: 603348,
        name: "Norman Fowler",
        email: "krajcik_mavis@june.net",
        phone: "344-817-4239",
        joiningDate: "2025-09-14",
        notes: "30 Albina Drive Apt. 284",
        status: "New",
        facebook: "asa",
        instagram: "as",
        website: "",
    },
];

export const campaignData = [
    {
        id: 101,
        name: "KFC",
        email: "kfc@example.com",
        phone: "555-1234",
        joiningDate: "2025-09-15",
        notes: "Interested in premium package",
        source: "Facebook Ads",
        status: "New",
        facebook: "xx",
        instagram: "xxx",
        website: "xxx",
    },
    {
        id: 102,
        name: "Garage Master Mall",
        email: "garage.master.mall@example.com",
        phone: "555-5678",
        joiningDate: "2025-09-14",
        notes: "Requested demo",
        source: "Google Campaign",
        status: "Pending",
        facebook: "asd",
        instagram: "",
        website: "asd",
    },
    {
        id: 103,
        name: "Pizza Hut",
        email: "pizzahut@example.com",
        phone: "555-8765",
        joiningDate: "2025-09-13",
        notes: "Wants enterprise plan",
        source: "LinkedIn Outreach",
        status: "Approved",
        facebook: "",
        instagram: "ss",
        website: "",
    },
    {
        id: 104,
        name: "Burger King",
        email: "bk@example.com",
        phone: "555-4321",
        joiningDate: "2025-09-12",
        notes: "Follow-up scheduled",
        source: "Referral",
        status: "Copy Writing",
        facebook: "",
        instagram: "sssss",
        website: " sdad",
    },
    {
        id: 105,
        name: "Domino’s Pizza",
        email: "dominos@example.com",
        phone: "555-6789",
        joiningDate: "2025-09-11",
        notes: "Requested pricing details",
        source: "Cold Email",
        status: "Shooting",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 106,
        name: "Starbucks",
        email: "starbucks@example.com",
        phone: "555-2468",
        joiningDate: "2025-09-10",
        notes: "Interested in trial",
        source: "Instagram Ads",
        status: "Design",
        facebook: "",
        instagram: "",
        website: "ss",
    },
    {
        id: 107,
        name: "Subway",
        email: "subway@example.com",
        phone: "555-1357",
        joiningDate: "2025-09-09",
        notes: "Needs integration support",
        source: "YouTube Ads",
        status: "Targeting",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 108,
        name: "McDonald’s",
        email: "mcdonalds@example.com",
        phone: "555-9753",
        joiningDate: "2025-09-08",
        notes: "Meeting scheduled",
        source: "Direct Website Signup",
        status: "Approved",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 109,
        name: "Taco Bell",
        email: "tacobell@example.com",
        phone: "555-8642",
        joiningDate: "2025-09-07",
        notes: "Looking for discount",
        source: "Facebook Ads",
        status: "Copy Writing",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 110,
        name: "Wendy’s",
        email: "wendys@example.com",
        phone: "555-7531",
        joiningDate: "2025-09-06",
        notes: "Demo completed",
        source: "Google Campaign",
        status: "Shooting",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 111,
        name: "Papa John’s",
        email: "papajohns@example.com",
        phone: "555-6420",
        joiningDate: "2025-09-05",
        notes: "Decision pending",
        source: "LinkedIn Outreach",
        status: "Completed",
        facebook: "asd",
        instagram: "",
        website: "asdad",
    },
    {
        id: 112,
        name: "Shake Shack",
        email: "shakeshack@example.com",
        phone: "555-5319",
        joiningDate: "2025-09-04",
        notes: "Very interested",
        source: "Referral",
        status: "Lost",
        facebook: "",
        instagram: "asd",
        website: "",
    },
    {
        id: 113,
        name: "KFC",
        email: "kfc@example.com",
        phone: "555-1234",
        joiningDate: "2025-09-15",
        notes: "Interested in premium package",
        source: "Facebook Ads",
        status: "New",
        facebook: "xx",
        instagram: "xxx",
        website: "xxx",
    },
    {
        id: 114,
        name: "Garage Master Mall",
        email: "garage.master.mall@example.com",
        phone: "555-5678",
        joiningDate: "2025-09-14",
        notes: "Requested demo",
        source: "Google Campaign",
        status: "Pending",
        facebook: "asd",
        instagram: "",
        website: "asd",
    },
    {
        id: 115,
        name: "Pizza Hut",
        email: "pizzahut@example.com",
        phone: "555-8765",
        joiningDate: "2025-09-13",
        notes: "Wants enterprise plan",
        source: "LinkedIn Outreach",
        status: "Approved",
        facebook: "",
        instagram: "ss",
        website: "",
    },
    {
        id: 116,
        name: "Burger King",
        email: "bk@example.com",
        phone: "555-4321",
        joiningDate: "2025-09-12",
        notes: "Follow-up scheduled",
        source: "Referral",
        status: "Copy Writing",
        facebook: "",
        instagram: "sssss",
        website: " sdad",
    },
    {
        id: 117,
        name: "Domino’s Pizza",
        email: "dominos@example.com",
        phone: "555-6789",
        joiningDate: "2025-09-11",
        notes: "Requested pricing details",
        source: "Cold Email",
        status: "Shooting",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 118,
        name: "Starbucks",
        email: "starbucks@example.com",
        phone: "555-2468",
        joiningDate: "2025-09-10",
        notes: "Interested in trial",
        source: "Instagram Ads",
        status: "Design",
        facebook: "",
        instagram: "",
        website: "ss",
    },
    {
        id: 119,
        name: "Subway",
        email: "subway@example.com",
        phone: "555-1357",
        joiningDate: "2025-09-09",
        notes: "Needs integration support",
        source: "YouTube Ads",
        status: "Targeting",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 120,
        name: "McDonald’s",
        email: "mcdonalds@example.com",
        phone: "555-9753",
        joiningDate: "2025-09-08",
        notes: "Meeting scheduled",
        source: "Direct Website Signup",
        status: "Approved",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 121,
        name: "Taco Bell",
        email: "tacobell@example.com",
        phone: "555-8642",
        joiningDate: "2025-09-07",
        notes: "Looking for discount",
        source: "Facebook Ads",
        status: "Copy Writing",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 122,
        name: "Wendy’s",
        email: "wendys@example.com",
        phone: "555-7531",
        joiningDate: "2025-09-06",
        notes: "Demo completed",
        source: "Google Campaign",
        status: "Shooting",
        facebook: "",
        instagram: "",
        website: "",
    },
    {
        id: 123,
        name: "Papa John’s",
        email: "papajohns@example.com",
        phone: "555-6420",
        joiningDate: "2025-09-05",
        notes: "Decision pending",
        source: "LinkedIn Outreach",
        status: "Completed",
        facebook: "asd",
        instagram: "",
        website: "asdad",
    },
    {
        id: 124,
        name: "Shake Shack",
        email: "shakeshack@example.com",
        phone: "555-5319",
        joiningDate: "2025-09-04",
        notes: "Very interested",
        source: "Referral",
        status: "Lost",
        facebook: "",
        instagram: "asd",
        website: "",
    },
];

export const getTableColumns = (t) => [
    { key: "id", label: t("#") },
    { key: "name", label: t("Name") },
    { key: "email", label: t("Email") },
    { key: "phone", label: t("Phone"), sortable: false },
    { key: "joiningDate", label: t("Joining Date") },
    { key: "notes", label: t("Note"), sortable: false },
    { key: "social", label: t("Social"), sortable: false },
    { key: "status", label: t("Status") },
    { key: "action", label: t("Action"), sortable: false },
];

export const dealsData = [
    {
        id: 201,
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        status: "New",
        value: 50000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 102,
        name: "Garage Master Mall",
        email: "garage.master.mall@example.com",
        phone: "555-5678",
        value: 760000,
        joiningDate: "2025-09-14",
        notes: "Requested demo",
        source: "Google Campaign",
        status: "Approved",
        facebook: "asd",
        instagram: "",
        website: "asd",
        isFinished: true,
    },
    {
        id: 103,
        name: "Pizza Hut",
        email: "pizzahut@example.com",
        phone: "555-8765",
        value: 430000,
        joiningDate: "2025-09-13",
        notes: "Wants enterprise plan",
        source: "LinkedIn Outreach",
        status: "New",
        facebook: "",
        instagram: "ss",
        website: "",
        isFinished: false,
    },
    {
        id: 202,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Approved",
        value: 120000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: true,
    },
    {
        id: 205,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Approved",
        value: 165000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 106,
        name: "Starbucks",
        email: "starbucks@example.com",
        phone: "555-2468",
        joiningDate: "2025-09-10",
        notes: "Interested in trial",
        source: "Instagram Ads",
        value: 32000,
        status: "Design",
        facebook: "",
        instagram: "",
        website: "ss",
        isFinished: false,
    },
    {
        id: 107,
        name: "Subway",
        email: "subway@example.com",
        phone: "555-1357",
        joiningDate: "2025-09-09",
        value: 65000,
        notes: "Needs integration support",
        source: "YouTube Ads",
        status: "Targeting",
        facebook: "",
        instagram: "",
        website: "",
        isFinished: true,
    },
    {
        id: 212,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Copy Writing",
        value: 32000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 209,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "New",
        value: 850000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 245,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Copy Writing",
        value: 80000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: true,
    },
    {
        id: 289,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        status: "Pending",
        value: 55000,
        phone: "845-701-8112",
        joiningDate: "2025-09-14",
        notes: "781 Klocko Row",
        facebook: "asa",
        instagram: "as",
        website: "",
        isFinished: false,
    },
    {
        id: 223,
        name: "Metroshin",
        email: "metroshin@example.com",
        phone: "555-8765",
        value: 600000,
        joiningDate: "2025-09-13",
        notes: "Wants enterprise plan",
        source: "LinkedIn Outreach",
        status: "New",
        facebook: "",
        instagram: "ss",
        website: "",
        isFinished: false,
    },
];

export const expensesColumns = [
    { key: "dealId", label: "Deal", sortable: true },
    { key: "salesManager", label: "Sales Manager / PM", sortable: true },
    { key: "copyWriter", label: "Copywriter", sortable: true },
    { key: "designer", label: "Designer", sortable: true },
    { key: "targeting", label: "Targeting", sortable: true },
    { key: "shooting", label: "Shooting", sortable: true },
    { key: "other", label: "Other (Notes)", sortable: false },
    { key: "total", label: "Total", sortable: true },
    { key: "action", label: "Action", sortable: false },
];

export const rolesConfig = {
    Admin: { access: ["all"] },
    Manager: { access: ["all"] },
    SalesManager: { access: ["clients", "campaign", "deals", "packages"], restricted: ["statistics"] },
    PM: { access: ["clients", "campaign", "deals", "packages"], restricted: ["statistics"] },
    Copywriter: { access: ["Copy Writing"], restricted: ["all"] },
    Reelmaker: { access: ["Shooting"], restricted: ["all"] },
    Designer: { access: ["Design"], restricted: ["all"] },
    Targetolog: { access: ["Targeting"], restricted: ["all"] }
};

export const dealsColumns = [
    "New", "Pending", "Approved", "Copy Writing", "Shooting", "Design",
    "Targeting", "Completed", "Lost",
];

export function getDealsColumnsForRole(role) {
    const roleConfig = rolesConfig[role];
    if (!roleConfig) return [];
    if (roleConfig.access.includes("all") || roleConfig.access.includes("deals")) return dealsColumns;

    return dealsColumns.filter(col => roleConfig.access.includes(col));
}
